harq_uber:
  outputs:
    dev:
      catalog: uber_dbt
      host: dbc-ea7d354d-6bb6.cloud.databricks.com
      http_path: /sql/1.0/warehouses/39a3792d3997afa7
      schema: source
      threads: 1
      token: token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev

